// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gknqdwmjxetwaxwlmzde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrbnFkd21qeGV0d2F4d2xtemRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTIzNzEsImV4cCI6MjA1ODgyODM3MX0.9Fp44HDilTUT6w5buhyo1JxGB44MSxh_1SvYIEo9ags";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);